import type { Product } from "../../../shared/types.js";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "gid://shopify/Product/1",
    handle: "adidas-samba-og-black",
    title: "Adidas Samba OG",
    description: "The iconic Samba silhouette in core black. Premium leather upper with suede T-toe overlay and gum rubber outsole.",
    vendor: "Adidas",
    productType: "Sneakers",
    tags: ["sneakers", "classic", "leather", "daily-wear"],
    images: [{ url: "https://placehold.co/400x400/111/fff?text=Samba+OG", altText: "Adidas Samba OG Black", width: 400, height: 400 }],
    options: [{ name: "Size", values: ["40", "41", "42", "43", "44", "45"] }],
    variants: [
      { id: "gid://shopify/ProductVariant/101", title: "40", availableForSale: true, quantityAvailable: 3, price: { amount: "120.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "40" }], image: null },
      { id: "gid://shopify/ProductVariant/102", title: "41", availableForSale: true, quantityAvailable: 5, price: { amount: "120.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "41" }], image: null },
      { id: "gid://shopify/ProductVariant/103", title: "42", availableForSale: true, quantityAvailable: 2, price: { amount: "120.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "42" }], image: null },
      { id: "gid://shopify/ProductVariant/104", title: "43", availableForSale: true, quantityAvailable: 4, price: { amount: "120.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "43" }], image: null },
      { id: "gid://shopify/ProductVariant/105", title: "44", availableForSale: false, quantityAvailable: 0, price: { amount: "120.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "44" }], image: null },
      { id: "gid://shopify/ProductVariant/106", title: "45", availableForSale: true, quantityAvailable: 1, price: { amount: "120.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "45" }], image: null },
    ],
    priceRange: { minVariantPrice: { amount: "120.00", currencyCode: "USD" }, maxVariantPrice: { amount: "120.00", currencyCode: "USD" } },
    metafields: { fitProfile: "True to size", materialSummary: "Premium leather upper, suede overlay", recommendedUse: "Daily wear, casual", authenticityNote: "100% authentic — sourced from authorized Adidas distributors" },
  },
  {
    id: "gid://shopify/Product/2",
    handle: "nike-air-force-1-07-white",
    title: "Nike Air Force 1 '07",
    description: "The classic AF1 in triple white. Full-grain leather upper, Air-Sole cushioning, and the original pivot-point outsole.",
    vendor: "Nike",
    productType: "Sneakers",
    tags: ["sneakers", "classic", "leather", "white", "daily-wear"],
    images: [{ url: "https://placehold.co/400x400/111/fff?text=AF1+White", altText: "Nike Air Force 1 White", width: 400, height: 400 }],
    options: [{ name: "Size", values: ["40", "41", "42", "43", "44", "45", "46"] }],
    variants: [
      { id: "gid://shopify/ProductVariant/201", title: "40", availableForSale: true, quantityAvailable: 6, price: { amount: "110.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "40" }], image: null },
      { id: "gid://shopify/ProductVariant/202", title: "41", availableForSale: true, quantityAvailable: 4, price: { amount: "110.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "41" }], image: null },
      { id: "gid://shopify/ProductVariant/203", title: "42", availableForSale: true, quantityAvailable: 8, price: { amount: "110.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "42" }], image: null },
      { id: "gid://shopify/ProductVariant/204", title: "43", availableForSale: true, quantityAvailable: 3, price: { amount: "110.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "43" }], image: null },
      { id: "gid://shopify/ProductVariant/205", title: "44", availableForSale: true, quantityAvailable: 5, price: { amount: "110.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "44" }], image: null },
      { id: "gid://shopify/ProductVariant/206", title: "45", availableForSale: true, quantityAvailable: 2, price: { amount: "110.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "45" }], image: null },
      { id: "gid://shopify/ProductVariant/207", title: "46", availableForSale: false, quantityAvailable: 0, price: { amount: "110.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "46" }], image: null },
    ],
    priceRange: { minVariantPrice: { amount: "110.00", currencyCode: "USD" }, maxVariantPrice: { amount: "110.00", currencyCode: "USD" } },
    metafields: { fitProfile: "Runs slightly large — consider half size down", materialSummary: "Full-grain leather", recommendedUse: "Daily wear, streetwear", authenticityNote: "100% authentic Nike" },
  },
  {
    id: "gid://shopify/Product/3",
    handle: "new-balance-550-white-green",
    title: "New Balance 550 White Green",
    description: "Retro basketball silhouette with a modern edge. Leather upper in white with green accents. ENCAP midsole cushioning.",
    vendor: "New Balance",
    productType: "Sneakers",
    tags: ["sneakers", "retro", "basketball", "leather", "white", "green"],
    images: [{ url: "https://placehold.co/400x400/111/fff?text=NB+550", altText: "New Balance 550 White Green", width: 400, height: 400 }],
    options: [{ name: "Size", values: ["40", "41", "42", "43", "44", "45"] }],
    variants: [
      { id: "gid://shopify/ProductVariant/301", title: "40", availableForSale: true, quantityAvailable: 2, price: { amount: "130.00", currencyCode: "USD" }, compareAtPrice: { amount: "150.00", currencyCode: "USD" }, selectedOptions: [{ name: "Size", value: "40" }], image: null },
      { id: "gid://shopify/ProductVariant/302", title: "41", availableForSale: true, quantityAvailable: 3, price: { amount: "130.00", currencyCode: "USD" }, compareAtPrice: { amount: "150.00", currencyCode: "USD" }, selectedOptions: [{ name: "Size", value: "41" }], image: null },
      { id: "gid://shopify/ProductVariant/303", title: "42", availableForSale: false, quantityAvailable: 0, price: { amount: "130.00", currencyCode: "USD" }, compareAtPrice: { amount: "150.00", currencyCode: "USD" }, selectedOptions: [{ name: "Size", value: "42" }], image: null },
      { id: "gid://shopify/ProductVariant/304", title: "43", availableForSale: true, quantityAvailable: 1, price: { amount: "130.00", currencyCode: "USD" }, compareAtPrice: { amount: "150.00", currencyCode: "USD" }, selectedOptions: [{ name: "Size", value: "43" }], image: null },
      { id: "gid://shopify/ProductVariant/305", title: "44", availableForSale: true, quantityAvailable: 4, price: { amount: "130.00", currencyCode: "USD" }, compareAtPrice: { amount: "150.00", currencyCode: "USD" }, selectedOptions: [{ name: "Size", value: "44" }], image: null },
      { id: "gid://shopify/ProductVariant/306", title: "45", availableForSale: false, quantityAvailable: 0, price: { amount: "130.00", currencyCode: "USD" }, compareAtPrice: { amount: "150.00", currencyCode: "USD" }, selectedOptions: [{ name: "Size", value: "45" }], image: null },
    ],
    priceRange: { minVariantPrice: { amount: "130.00", currencyCode: "USD" }, maxVariantPrice: { amount: "130.00", currencyCode: "USD" } },
    metafields: { fitProfile: "True to size", materialSummary: "Leather upper, rubber outsole", recommendedUse: "Casual, lifestyle", styleTags: ["retro", "court", "clean"] },
  },
  {
    id: "gid://shopify/Product/4",
    handle: "adidas-gazelle-bold-black",
    title: "Adidas Gazelle Bold",
    description: "The Gazelle reimagined with a stacked platform midsole. Suede upper in core black with gold foil branding.",
    vendor: "Adidas",
    productType: "Sneakers",
    tags: ["sneakers", "platform", "suede", "black", "bold"],
    images: [{ url: "https://placehold.co/400x400/111/fff?text=Gazelle+Bold", altText: "Adidas Gazelle Bold Black", width: 400, height: 400 }],
    options: [{ name: "Size", values: ["36", "37", "38", "39", "40", "41", "42"] }],
    variants: [
      { id: "gid://shopify/ProductVariant/401", title: "36", availableForSale: true, quantityAvailable: 2, price: { amount: "140.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "36" }], image: null },
      { id: "gid://shopify/ProductVariant/402", title: "37", availableForSale: true, quantityAvailable: 3, price: { amount: "140.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "37" }], image: null },
      { id: "gid://shopify/ProductVariant/403", title: "38", availableForSale: true, quantityAvailable: 1, price: { amount: "140.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "38" }], image: null },
      { id: "gid://shopify/ProductVariant/404", title: "39", availableForSale: true, quantityAvailable: 4, price: { amount: "140.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "39" }], image: null },
      { id: "gid://shopify/ProductVariant/405", title: "40", availableForSale: false, quantityAvailable: 0, price: { amount: "140.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "40" }], image: null },
      { id: "gid://shopify/ProductVariant/406", title: "41", availableForSale: true, quantityAvailable: 2, price: { amount: "140.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "41" }], image: null },
      { id: "gid://shopify/ProductVariant/407", title: "42", availableForSale: true, quantityAvailable: 1, price: { amount: "140.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "42" }], image: null },
    ],
    priceRange: { minVariantPrice: { amount: "140.00", currencyCode: "USD" }, maxVariantPrice: { amount: "140.00", currencyCode: "USD" } },
    metafields: { fitProfile: "True to size", materialSummary: "Premium suede upper", recommendedUse: "Fashion, lifestyle, going out" },
  },
  {
    id: "gid://shopify/Product/5",
    handle: "nike-dunk-low-panda",
    title: "Nike Dunk Low Retro 'Panda'",
    description: "The Dunk Low in the iconic black and white 'Panda' colorway. Leather upper, foam midsole, rubber cupsole.",
    vendor: "Nike",
    productType: "Sneakers",
    tags: ["sneakers", "retro", "leather", "black", "white", "dunk"],
    images: [{ url: "https://placehold.co/400x400/111/fff?text=Dunk+Panda", altText: "Nike Dunk Low Panda", width: 400, height: 400 }],
    options: [{ name: "Size", values: ["40", "41", "42", "43", "44", "45"] }],
    variants: [
      { id: "gid://shopify/ProductVariant/501", title: "40", availableForSale: true, quantityAvailable: 4, price: { amount: "115.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "40" }], image: null },
      { id: "gid://shopify/ProductVariant/502", title: "41", availableForSale: true, quantityAvailable: 2, price: { amount: "115.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "41" }], image: null },
      { id: "gid://shopify/ProductVariant/503", title: "42", availableForSale: true, quantityAvailable: 6, price: { amount: "115.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "42" }], image: null },
      { id: "gid://shopify/ProductVariant/504", title: "43", availableForSale: false, quantityAvailable: 0, price: { amount: "115.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "43" }], image: null },
      { id: "gid://shopify/ProductVariant/505", title: "44", availableForSale: true, quantityAvailable: 3, price: { amount: "115.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "44" }], image: null },
      { id: "gid://shopify/ProductVariant/506", title: "45", availableForSale: true, quantityAvailable: 1, price: { amount: "115.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "45" }], image: null },
    ],
    priceRange: { minVariantPrice: { amount: "115.00", currencyCode: "USD" }, maxVariantPrice: { amount: "115.00", currencyCode: "USD" } },
    metafields: { fitProfile: "True to size", materialSummary: "Leather upper, foam midsole", recommendedUse: "Daily wear, streetwear", styleTags: ["classic", "versatile", "clean"] },
  },
  {
    id: "gid://shopify/Product/6",
    handle: "jordan-1-low-olive",
    title: "Air Jordan 1 Low SE 'Olive'",
    description: "The AJ1 Low in an olive and sail colorway. Leather and nubuck upper with Air-Sole heel unit.",
    vendor: "Jordan",
    productType: "Sneakers",
    tags: ["sneakers", "jordan", "leather", "olive", "green"],
    images: [{ url: "https://placehold.co/400x400/111/fff?text=AJ1+Olive", altText: "Air Jordan 1 Low Olive", width: 400, height: 400 }],
    options: [{ name: "Size", values: ["41", "42", "43", "44", "45"] }],
    variants: [
      { id: "gid://shopify/ProductVariant/601", title: "41", availableForSale: true, quantityAvailable: 2, price: { amount: "135.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "41" }], image: null },
      { id: "gid://shopify/ProductVariant/602", title: "42", availableForSale: true, quantityAvailable: 3, price: { amount: "135.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "42" }], image: null },
      { id: "gid://shopify/ProductVariant/603", title: "43", availableForSale: true, quantityAvailable: 1, price: { amount: "135.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "43" }], image: null },
      { id: "gid://shopify/ProductVariant/604", title: "44", availableForSale: true, quantityAvailable: 2, price: { amount: "135.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "44" }], image: null },
      { id: "gid://shopify/ProductVariant/605", title: "45", availableForSale: false, quantityAvailable: 0, price: { amount: "135.00", currencyCode: "USD" }, compareAtPrice: null, selectedOptions: [{ name: "Size", value: "45" }], image: null },
    ],
    priceRange: { minVariantPrice: { amount: "135.00", currencyCode: "USD" }, maxVariantPrice: { amount: "135.00", currencyCode: "USD" } },
    metafields: { fitProfile: "True to size", materialSummary: "Leather and nubuck", recommendedUse: "Casual, versatile" },
  },
];
